[project]
name = "03-project03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.8.0",
    "fastembed>=0.8.1",
    "google-cloud-modelarmor>=0.7.1",
    "google-cloud-storage>=3.14.1",
    "langchain>=1.0,<2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.0,<2",
    "langchain-google-genai>=4.4.0",
    "langchain-litellm>=0.8.0",
    "langchain-openai>=1.6.5",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=0.2",
    "langgraph-cli[inmem]>=0.4.32",
    "langsmith>=0.14.0",
    "litellm>=1.102.1",
    "numpy>=2.5.3",
    "openevals>=0.2.0",
    "pydantic>=2.13.5",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-pptx>=1.0.2",
    "qdrant-client>=1.19.1",
    "requests>=2.34.2",
    "streamlit>=1.64.0",
]
